export const Accounts = {
  dbTable: 'accounts',
  columns: [
    {
      group: -1,
      where: 1,
      ordr: 1,
      field: "acctID",
      dbCol: "id",
      label: "",
      width: 0,
      dataType: "INT",
      setVar: ":acctID",
    },
    {
      group: 1,
      ordr: 2,
      field: "acctName",
      dbCol: "name",
      label: "Account Name",
      width: 200,
      dataType: "STRING",
      required: 1,
      setVar: ":acctName",
    },
    {
      group: 2,
      ordr: 3,
      field: "acctDesc",
      dbCol: "description",
      label: "Description",
      width: 300,
      dataType: "STRING",
      required: 0,
      setVar: ":acctDesc",
    },
    {
      group: 3,
      ordr: 4,
      field: "acctAddr",
      dbCol: "street_address",
      label: "Address",
      width: 150,
      dataType: "STRING",
      required: 0,
      setVar: ":acctAddr",
    },
    {
      group: 3,
      ordr: 5,
      field: "acctCity",
      dbCol: "city",
      label: "City",
      width: 150,
      dataType: "STRING",
      required: 0,
      setVar: ":acctCity",
    },
    {
      group: 3,
      ordr: 6,
      field: "acctState",
      dbCol: "state_code",
      label: "State",
      width: 120,
      dataType: "STRING",
      setVar: ":acctState",
    },
    {
      group: 3,
      ordr: 7,
      field: "acctZipCode",
      dbCol: "zip_code",
      label: "Zip",
      width: 100,
      dataType: "STRING",
      required: 1,
      setVar: ":acctZipCode",
    },
    {
      group: 6,
      ordr: 8,
      field: "acctCompCode",
      dbCol: "company_code",
      label: "UPC Company Code",
      width: 150,
      dataType: "STRING",
      required: 0,
      setVar: ":acctCompCode",
    },
    {
      group: 4,
      ordr: 9,
      field: "acctDfltLoc",
      dbCol: "default_location",
      label: "Make Location",
      width: 150,
      dataType: "STRING",
      required: 1,
      setVar: ":acctDfltLoc",
    },
    {
      group: 5,
      ordr: 10,
      field: "acctURL",
      dbCol: "url",
      label: "Website",
      width: 150,
      dataType: "STRING",
      required: 0,
      setVar: ":acctURL",
    },
    {
      group: 6,
      ordr: 11,
      field: "acctPayCustCode",
      dbCol: "payment_customer_code",
      label: "Stripe: Pay Code",
      width: 150,
      dataType: "STRING",
      required: 0,
      setVar: ":acctPayCustCode",
    },
    {
      group: 6,
      ordr: 12,
      field: "acctSubsptnCode",
      dbCol: "payment_subscription_code",
      label: "Stripe: Subscription Code",
      width: 150,
      dataType: "STRING",
      required: 0,
      setVar: ":acctSubsptnCode",
    }
  ]
};

export default Accounts;
