flowchart TD
    A[Provider Tree] -->|Data Hierarchy| C(Global: User & Account)
    C --> E(EventType)
    E --> F(Ingredients)
    E --> G(Products)
    F --> H(IngrType)
    H --> I(Ingr)
    I --> J(IngrBtch)
    G --> K(ProdType)
    K --> L(Prod)
    G --> N(Tasks)
    L --> M(Recipe)
    K --> O(ProdBtch)
    I --> M
    O --> P(Map Batches)
    M --> P
    J --> P
    E --> Q(Workers)
    E --> R(Brands)
    E --> S(Vendors)
    R --> |Not Required|J
    S --> J
    O --> T(ProdBtchTask)
    N --> Tasks
    Q --> |Not Reqired| T


    
  