name: Auto-Assign Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: lyzidiamond/add-to-github-projects@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
          project-url: https://github.com/users/pchambless/projects/4  # Replace with your project URL
          content-id: ${{ github.event.issue.node_id }}  # The issue ID
