name: Auto-Assign Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Run GraphQL Query
        uses: octokit/graphql-action@v1
        with:
          query: |
            mutation($projectId: ID!, $contentId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                item {
                  id
                }
              }
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
          variables: |
            {
              "projectId": "YOUR_PROJECT_ID",
              "contentId": "${{ github.event.issue.node_id }}"
            }
