name: Auto-Assign Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: @Whatsfresh Requirements
          column: BackLog
          issue-number: ${{ github.event.issue.number }}
